### ISSUE TITLE
Background too dark in search result with light theme

### ISSUE THREAD

**Issue by Elm7** [Eskuero/collapsed_mastodon#2]
Hi, thanks a lot for the addon.
I report that the background is too dark in search result with light theme.
![capture d ecran_2018-11-11_22-19-44](https://user-images.githubusercontent.com/11534708/48318384-3ea21c00-e600-11e8-93c8-cb4629c5398a.png)
Have a great day.

**Comment by Eskuero** [comment]
This is indeed true, as of now we have been hardcoding the background color but we should get it from the theme settings.

Should not be hard to do. Thanks for reporting!

**Comment by Eskuero** [comment]
Fixed on b4e26f4
